### ISSUE TITLE
Rename project to UoPeople-Enhancer

### ISSUE THREAD

**Issue by DanJFletcher** [Ignas2526/UoP-Enahncer#1]
UoP is in fact another university called University of Pheonox. This is why there is so much fuss about using the proper abbreviation (UoPeople). UoP is a for-profit institution and has a bad reputation. UoPeople on the other hand is a non-profit - with a hopefully better reputation.

At the very least, all mentions of UoP in the readme and any other future documentation should be changed to UoPeople.

Great project by the way!

**Comment by ignas2526** [comment]
I've renamed the repository and the files.

**Comment by DanJFletcher** [comment]
Great!
